
version: "3"

services:
  nginx:
    image: nginx:stable-alpine
    networks:
      - atividade-docker
    container_name: nginx
    ports:
      - 8080:80

  mysql:
    image: mysql:latest
    networks:
      - atividade-docker
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "teste"
      MYSQL_DATABASE: "teste"

networks:
  atividade-docker:
    driver: bridge